# Generated by Django 4.1.1 on 2022-09-11 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_sheets', '0002_remove_googlesheets_id_googlesheets_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googlesheets',
            name='number',
            field=models.BigIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='№'),
        ),
    ]
